# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
exclude:             [CNAME, Gemfile, README.md, LICENSE.md, scratch.md]
unpublished:         true
show_drafts:         false
title:               没有国界的世界
tagline:             A World With No Boundaries
description:         '无聊的人用无聊的时间做的无聊的博客'
url:                 https://pixy.awwnb.org
baseurl:             ''
# About/contact
author:
  name:              Winston Sicheng Wu
  url:               https://pixy.awwnb.org
  email:             winstonw@udel.edu

# Custom data
established:         2014
license:             CC BY 4.0
license_url:         http://creativecommons.org/licenses/by/4.0/legalcode
